version: '3'
services:
  db:
    image: postgres:13.1
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
 #   volumes:
 #     - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: docker_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  #    PGDATA: /var/lib/postgresql/data/pgdata

  java-base:
    image: openjdk:8
    working_dir: /var/www
    ports:
      - '8080:8080'
    volumes:
      - ./target:/var/www
    command: java -jar docker-spring_boot-0.0.1-SNAPSHOT.jar
    depends_on:
      - db